# This file contains secrets and should NOT be committed to git!
jwt:
  secret: MySuperSuperSecretKeyThatIsVeryLongAndSecureAndShouldBeKeptVerySafeNoMatterWhat

datasource:
  password: your_db_password

cloudinary:
  api_key: your_cloudinary_key
  api_secret: your_cloudinary_secret
